# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-07-12 19:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helvetic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='measurement', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scale',
            name='users',
            field=models.ManyToManyField(blank=True, help_text=b'UserProfiles for the users of this scale.', related_name='used_scales', to='helvetic.UserProfile'),
        ),
    ]
